///**********************************************************************************************************************
// * \file Can_TxInput.c
// * \copyright Copyright (C) Infineon Technologies AG 2019
// *
// * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
// * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
// * are agreed, use of this file is subject to following:
// *
// * Boost Software License - Version 1.0 - August 17th, 2003
// *
// * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
// * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
// * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
// * Software is furnished to do so, all subject to the following:
// *
// * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
// * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
// * derivative works of the Software, unless such copies or derivative works are solely in the form of
// * machine-executable object code generated by a source language processor.
// *
// * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
// * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
// * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
// * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
// * IN THE SOFTWARE.
// *********************************************************************************************************************/
//
//
///*********************************************************************************************************************/
///*-----------------------------------------------------Includes------------------------------------------------------*/
//#include "Can_TxInput.h"
//#include "IfxMultican_Can.h"
//#include "IfxPort.h"
//#include <stddef.h>
///*********************************************************************************************************************/
//
///*********************************************************************************************************************/
///*------------------------------------------------------Macros-------------------------------------------------------*/
//#define CAN_TXINPUT_NODE_ID                 IfxMultican_NodeId_0
//#define CAN_TXINPUT_BAUDRATE                (500000U)
//#define CAN_TXINPUT_TX_MSGOBJ_ID            (0U)
//
///*
// * ShieldBuddy TC275에서 자주 쓰는 CAN0 핀 예시
// * 실제 네 트랜시버 배선이 다르면 아래 두 매크로만 바꿔라.
// */
//#define CAN_TXINPUT_RX_PIN                  IfxMultican_RXD0B_P20_7_IN
//#define CAN_TXINPUT_TX_PIN                  IfxMultican_TXD0_P20_8_OUT
///*********************************************************************************************************************/
//
///*********************************************************************************************************************/
///*-------------------------------------------------Global variables--------------------------------------------------*/
///*********************************************************************************************************************/
//
///*********************************************************************************************************************/
///*--------------------------------------------Private Variables/Constants--------------------------------------------*/
//static IfxMultican_Can        g_multican;
//static IfxMultican_Can_Node   g_canNode;
//static IfxMultican_Can_MsgObj g_canTxMsgObj;
///*********************************************************************************************************************/
//
///*********************************************************************************************************************/
///*------------------------------------------------Function Prototypes------------------------------------------------*/
//static uint16 Can_TxInput_EncodeSteerRaw(uint16 steerAngleDeg);
//static void Can_TxInput_BuildMessage(const If_InputEcuData_t* data, IfxMultican_Message* message);
///*********************************************************************************************************************/
//
///*********************************************************************************************************************/
///*---------------------------------------------Function Implementations----------------------------------------------*/
//void Can_TxInput_Init(void)
//{
//    IfxMultican_Can_Config canConfig;
//    IfxMultican_Can_NodeConfig nodeConfig;
//    IfxMultican_Can_MsgObjConfig msgObjConfig;
//
//    IfxMultican_Can_initModuleConfig(&canConfig, &MODULE_CAN);
//    IfxMultican_Can_initModule(&g_multican, &canConfig);
//
//    IfxMultican_Can_Node_initConfig(&nodeConfig, &g_multican);
//    nodeConfig.nodeId = CAN_TXINPUT_NODE_ID;
//    nodeConfig.baudrate = CAN_TXINPUT_BAUDRATE;
//    nodeConfig.rxPin = &CAN_TXINPUT_RX_PIN;
//    nodeConfig.txPin = &CAN_TXINPUT_TX_PIN;
//    nodeConfig.txPinMode = IfxPort_OutputMode_pushPull;
//    nodeConfig.pinDriver = IfxPort_PadDriver_cmosAutomotiveSpeed1;
//
//    IfxMultican_Can_Node_init(&g_canNode, &nodeConfig);
//
//    IfxMultican_Can_MsgObj_initConfig(&msgObjConfig, &g_canNode);
//    msgObjConfig.msgObjId = CAN_TXINPUT_TX_MSGOBJ_ID;
//    msgObjConfig.messageId = CAN_TXINPUT_MSG_ID_INPUT_DATA;
//    msgObjConfig.frame = IfxMultican_Frame_transmit;
//    msgObjConfig.messageLen = IfxMultican_DataLengthCode_8;
//    msgObjConfig.control.matchingId = TRUE;
//    msgObjConfig.control.extendedFrame = FALSE;
//    msgObjConfig.control.txInterrupt.enabled = FALSE;
//    msgObjConfig.control.rxInterrupt.enabled = FALSE;
//
//    IfxMultican_Can_MsgObj_init(&g_canTxMsgObj, &msgObjConfig);
//}
//
//void Can_TxInput_Send(const If_InputEcuData_t* data)
//{
//    IfxMultican_Message message;
//
//    if (data == NULL_PTR)
//    {
//        return;
//    }
//
//    Can_TxInput_BuildMessage(data, &message);
//
//    while (IfxMultican_Can_MsgObj_sendMessage(&g_canTxMsgObj, &message) == IfxMultican_Status_notSentBusy)
//    {
//        /* wait until message object becomes free */
//    }
//}
//
//static uint16 Can_TxInput_EncodeSteerRaw(uint16 steerAngleDeg)
//{
//    sint32 signedAngle;
//
//    signedAngle = (sint32)steerAngleDeg - 450;
//
//    if (signedAngle < -450)
//    {
//        signedAngle = -450;
//    }
//    else if (signedAngle > 450)
//    {
//        signedAngle = 450;
//    }
//    else
//    {
//        /* do nothing */
//    }
//
//    return (uint16)(signedAngle + 450);
//}
//
//static void Can_TxInput_BuildMessage(const If_InputEcuData_t* data, IfxMultican_Message* message)
//{
//    uint8 payload[8];
//    uint16 steerEncoded;
//    uint32 dataLow;
//    uint32 dataHigh;
//
//    payload[0] = (data->user_ack_button == true) ? 1U : 0U;
//
//    payload[1] = (uint8)(data->accel_pedal_value & 0xFFU);
//    payload[2] = (uint8)((data->accel_pedal_value >> 8) & 0xFFU);
//
//    payload[3] = (uint8)(data->brake_pedal_value & 0xFFU);
//    payload[4] = (uint8)((data->brake_pedal_value >> 8) & 0xFFU);
//
//    steerEncoded = Can_TxInput_EncodeSteerRaw(data->steer_angle_deg);
//    payload[5] = (uint8)(steerEncoded & 0xFFU);
//    payload[6] = (uint8)((steerEncoded >> 8) & 0xFFU);
//
//    payload[7] = (uint8)(((data->accel_valid & 0x01U) << 0) |
//                         ((data->brake_valid & 0x01U) << 1) |
//                         ((data->steer_valid & 0x01U) << 2));
//
//    dataLow =  ((uint32)payload[0] << 0)
//             | ((uint32)payload[1] << 8)
//             | ((uint32)payload[2] << 16)
//             | ((uint32)payload[3] << 24);
//
//    dataHigh = ((uint32)payload[4] << 0)
//             | ((uint32)payload[5] << 8)
//             | ((uint32)payload[6] << 16)
//             | ((uint32)payload[7] << 24);
//
//    IfxMultican_Message_init(message,
//                             CAN_TXINPUT_MSG_ID_INPUT_DATA,
//                             dataLow,
//                             dataHigh,
//                             IfxMultican_DataLengthCode_8);
//}
///*********************************************************************************************************************/
