/**********************************************************************************************************************
 * \file Drv_Button.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
#include "Drv_Button.h"
#include "IfxPort.h"
#include "Platform_Types.h"
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
#define DRV_BUTTON_PORT              (&MODULE_P00)
#define DRV_BUTTON_PIN               (4U)
#define DRV_BUTTON_ACTIVE_LEVEL      (0U)
#define DRV_BUTTON_DEBOUNCE_TICKS    (2U)
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
static bool s_buttonState = false;
static bool s_prevButtonState = false;
static bool s_pressedEvent = false;
static bool s_releasedEvent = false;
static uint16 s_debounceCnt = 0U;
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
static bool Drv_Button_ReadRawPressed(void);
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
void Drv_Button_Init(void)
{
    IfxPort_setPinModeInput(DRV_BUTTON_PORT, DRV_BUTTON_PIN, IfxPort_InputMode_pullUp);

    s_buttonState = false;
    s_prevButtonState = false;
    s_pressedEvent = false;
    s_releasedEvent = false;
    s_debounceCnt = 0U;
}

void Drv_Button_Task(void)
{
    bool rawPressed;
    bool newState;

    rawPressed = Drv_Button_ReadRawPressed();
    newState = rawPressed;

    if (newState != s_buttonState)
    {
        s_debounceCnt++;

        if (s_debounceCnt >= DRV_BUTTON_DEBOUNCE_TICKS)
        {
            s_prevButtonState = s_buttonState;
            s_buttonState = newState;
            s_debounceCnt = 0U;

            if ((s_prevButtonState == false) && (s_buttonState == true))
            {
                s_pressedEvent = true;
            }
            else if ((s_prevButtonState == true) && (s_buttonState == false))
            {
                s_releasedEvent = true;
            }
            else
            {
                /* do nothing */
            }
        }
    }
    else
    {
        s_debounceCnt = 0U;
    }
}

bool Drv_Button_GetState(void)
{
    return s_buttonState;
}

bool Drv_Button_GetPressedEvent(void)
{
    return s_pressedEvent;
}

bool Drv_Button_GetReleasedEvent(void)
{
    return s_releasedEvent;
}

void Drv_Button_ClearEvents(void)
{
    s_pressedEvent = false;
    s_releasedEvent = false;
}

static bool Drv_Button_ReadRawPressed(void)
{
    uint8 pinState;

    pinState = (uint8)IfxPort_getPinState(DRV_BUTTON_PORT, DRV_BUTTON_PIN);

    return (pinState == DRV_BUTTON_ACTIVE_LEVEL) ? true : false;
}
/*********************************************************************************************************************/
