/**********************************************************************************************************************
 * \file If_InputEcu.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software"), to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
#include "Platform_Types.h"
#include "If_InputEcu.h"
#include "Drv_Button.h"
#include "Drv_AdcInput.h"
#include <stdbool.h>
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
#define IF_INPUT_ADC_MIN             (0U)
#define IF_INPUT_ADC_MAX             (4095U)

/* 엑셀 홀센서 보정
 * raw = IF_INPUT_ACCEL_MIN  -> 0x0000
 * raw = IF_INPUT_ACCEL_MAX  -> 0xFFFF
 */
#define IF_INPUT_ACCEL_MIN           (0x0780U)
#define IF_INPUT_ACCEL_MAX           (0x0840U)

/* 브레이크 홀센서 보정
 * raw = IF_INPUT_BRAKE_MIN  -> 0x0000
 * raw = IF_INPUT_BRAKE_MAX  -> 0xFFFF
 */
#define IF_INPUT_BRAKE_MIN           (0x0780U)
#define IF_INPUT_BRAKE_MAX           (0x0860U)

/* 핸들 보정
 * raw = IF_INPUT_STEER_MIN  -> 0x0000
 * raw = IF_INPUT_STEER_MAX  -> 0xFFFF
 */
#define IF_INPUT_STEER_MIN           (140U)
#define IF_INPUT_STEER_MAX           (0x0A85U)
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
static If_InputEcuData_t s_inputData;
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
static uint16 If_InputEcu_IsInRange(uint16 raw, uint16 min, uint16 max);
static uint16 If_InputEcu_ClampAndScale(uint16 raw, uint16 min, uint16 max);
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
void If_InputEcu_Init(void)
{
    s_inputData.user_ack_button = Drv_Button_GetState();

    s_inputData.accel_pedal_value = 0U;
    s_inputData.brake_pedal_value = 0U;
    s_inputData.steer_angle_deg   = 0U;

    s_inputData.accel_valid = 0U;
    s_inputData.brake_valid = 0U;
    s_inputData.steer_valid = 0U;

    s_inputData.accel_raw = 0U;
    s_inputData.brake_raw = 0U;
    s_inputData.steer_raw = 0U;
}

void If_InputEcu_Task(void)
{
    uint16 accelRaw;
    uint16 brakeRaw;
    uint16 steerRaw;

    uint16 accelScaled;
    uint16 brakeScaled;
    uint16 steerScaled;

    accelRaw = Drv_AdcInput_GetFiltered(DRV_ADC_ACCEL);
    brakeRaw = Drv_AdcInput_GetFiltered(DRV_ADC_BRAKE);
    steerRaw = Drv_AdcInput_GetFiltered(DRV_ADC_STEER);

    s_inputData.accel_raw = accelRaw;
    s_inputData.brake_raw = brakeRaw;
    s_inputData.steer_raw = steerRaw;

    /* 🔥 여기 수정 */
    s_inputData.user_ack_button = Drv_Button_GetState();

    s_inputData.accel_valid = If_InputEcu_IsInRange(accelRaw, IF_INPUT_ADC_MIN, IF_INPUT_ADC_MAX);
    s_inputData.brake_valid = If_InputEcu_IsInRange(brakeRaw, IF_INPUT_ADC_MIN, IF_INPUT_ADC_MAX);
    s_inputData.steer_valid = If_InputEcu_IsInRange(steerRaw, IF_INPUT_ADC_MIN, IF_INPUT_ADC_MAX);

    /********************************************/
    /* accel: MIN~MAX -> 0~FFFF scale           */
    /********************************************/
    accelScaled = If_InputEcu_ClampAndScale(accelRaw, IF_INPUT_ACCEL_MIN, IF_INPUT_ACCEL_MAX);
    s_inputData.accel_pedal_value = accelScaled;

    /********************************************/
    /* brake: MIN~MAX -> 0~FFFF scale           */
    /********************************************/
    brakeScaled = If_InputEcu_ClampAndScale(brakeRaw, IF_INPUT_BRAKE_MIN, IF_INPUT_BRAKE_MAX);
    s_inputData.brake_pedal_value = brakeScaled;

    /********************************************/
    /* steer: MIN~MAX -> 0~FFFF scale           */
    /********************************************/
    steerScaled = If_InputEcu_ClampAndScale(steerRaw, IF_INPUT_STEER_MIN, IF_INPUT_STEER_MAX);
    s_inputData.steer_angle_deg = steerScaled;

    Drv_Button_ClearEvents();
}

const If_InputEcuData_t* If_InputEcu_GetData(void)
{
    return &s_inputData;
}

static uint16 If_InputEcu_IsInRange(uint16 raw, uint16 min, uint16 max)
{
    return ((raw >= min) && (raw <= max)) ? 1U : 0U;
}

static uint16 If_InputEcu_ClampAndScale(uint16 raw, uint16 min, uint16 max)
{
    uint16 clamped;
    uint16 normalized;
    uint16 range;

    if (max <= min)
    {
        return 0U;
    }

    if (raw <= min)
    {
        clamped = min;
    }
    else if (raw >= max)
    {
        clamped = max;
    }
    else
    {
        clamped = raw;
    }

    normalized = (uint16)(clamped - min);
    range = (uint16)(max - min);

    return (uint16)(((uint32)normalized * 65535U) / (uint32)range);
}
/*********************************************************************************************************************/
