/**********************************************************************************************************************
 * \file If_InputEcu.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
#include "Platform_Types.h"
#include "If_InputEcu.h"
#include "Drv_Button.h"
#include "Drv_AdcInput.h"
#include <stdbool.h>
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
#define IF_INPUT_ADC_MIN             (0U)
#define IF_INPUT_ADC_MAX             (4095U)
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
static If_InputEcuData_t s_inputData;
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
static uint16 If_InputEcu_IsInRange(uint16 raw, uint16 min, uint16 max);
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
void If_InputEcu_Init(void)
{
    s_inputData.user_ack_button = Drv_Button_GetState();

    s_inputData.accel_pedal_value = 0U;
    s_inputData.brake_pedal_value = 0U;
    s_inputData.steer_angle_deg   = 0U;

    s_inputData.accel_valid = 0U;
    s_inputData.brake_valid = 0U;
    s_inputData.steer_valid = 0U;

    s_inputData.accel_raw = 0U;
    s_inputData.brake_raw = 0U;
    s_inputData.steer_raw = 0U;
}

void If_InputEcu_Task(void)
{
    uint16 accelRaw;
    uint16 brakeRaw;
    uint16 steerRaw;

    static bool s_toggleState = false;   // ⭐ 추가 (핵심)

    accelRaw = Drv_AdcInput_GetFiltered(DRV_ADC_ACCEL);
    brakeRaw = Drv_AdcInput_GetFiltered(DRV_ADC_BRAKE);
    steerRaw = Drv_AdcInput_GetFiltered(DRV_ADC_STEER);

    s_inputData.accel_raw = accelRaw;
    s_inputData.brake_raw = brakeRaw;
    s_inputData.steer_raw = steerRaw;

    /* ⭐ 버튼 눌릴 때마다 토글 */
    if (Drv_Button_GetPressedEvent() == true)
    {
        s_toggleState = !s_toggleState;
    }

    s_inputData.user_ack_button = s_toggleState;

    s_inputData.accel_valid = If_InputEcu_IsInRange(accelRaw, IF_INPUT_ADC_MIN, IF_INPUT_ADC_MAX);
    s_inputData.brake_valid = If_InputEcu_IsInRange(brakeRaw, IF_INPUT_ADC_MIN, IF_INPUT_ADC_MAX);
    s_inputData.steer_valid = If_InputEcu_IsInRange(steerRaw, IF_INPUT_ADC_MIN, IF_INPUT_ADC_MAX);

    s_inputData.accel_pedal_value = accelRaw;
    s_inputData.brake_pedal_value = brakeRaw;
    s_inputData.steer_angle_deg   = steerRaw;

    Drv_Button_ClearEvents();
}

// 테스트용이니까 다시 이걸로 되돌려야 함
//void If_InputEcu_Task(void)
//{
//    uint16 accelRaw;
//    uint16 brakeRaw;
//    uint16 steerRaw;
//
//    accelRaw = Drv_AdcInput_GetFiltered(DRV_ADC_ACCEL);
//    brakeRaw = Drv_AdcInput_GetFiltered(DRV_ADC_BRAKE);
//    steerRaw = Drv_AdcInput_GetFiltered(DRV_ADC_STEER);
//
//    s_inputData.accel_raw = accelRaw;
//    s_inputData.brake_raw = brakeRaw;
//    s_inputData.steer_raw = steerRaw;
//
//    if (Drv_Button_GetPressedEvent() == true)
//    {
//        s_inputData.user_ack_button = true;
//    }
//    else
//    {
//        s_inputData.user_ack_button = false;
//    }
//
//    s_inputData.accel_valid = If_InputEcu_IsInRange(accelRaw, IF_INPUT_ADC_MIN, IF_INPUT_ADC_MAX);
//    s_inputData.brake_valid = If_InputEcu_IsInRange(brakeRaw, IF_INPUT_ADC_MIN, IF_INPUT_ADC_MAX);
//    s_inputData.steer_valid = If_InputEcu_IsInRange(steerRaw, IF_INPUT_ADC_MIN, IF_INPUT_ADC_MAX);
//
//    /* 최종 요구사항: 0~4095 raw 그대로 사용 */
//    s_inputData.accel_pedal_value = accelRaw;
//    s_inputData.brake_pedal_value = brakeRaw;
//    s_inputData.steer_angle_deg   = steerRaw;
//
//    Drv_Button_ClearEvents();
//}

const If_InputEcuData_t* If_InputEcu_GetData(void)
{
    return &s_inputData;
}

static uint16 If_InputEcu_IsInRange(uint16 raw, uint16 min, uint16 max)
{
    return ((raw >= min) && (raw <= max)) ? 1U : 0U;
}
/*********************************************************************************************************************/
