/**********************************************************************************************************************
 * \file If_InputEcu.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software"), to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
#include "Platform_Types.h"
#include "If_InputEcu.h"
#include "Drv_Button.h"
#include "Drv_AdcInput.h"
#include <stdbool.h>
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
#define IF_INPUT_ADC_MIN             (0U)
#define IF_INPUT_ADC_MAX             (4095U)

/* 엑셀 홀센서 보정
 * raw = IF_INPUT_ACCEL_MIN  -> 0
 * raw = IF_INPUT_ACCEL_MAX  -> 255
 */
#define IF_INPUT_ACCEL_MIN           (0x0750U)
#define IF_INPUT_ACCEL_MAX           (0x0860U)

/* 브레이크 홀센서 보정
 * raw = IF_INPUT_BRAKE_MIN  -> 0
 * raw = IF_INPUT_BRAKE_MAX  -> 255
 */
#define IF_INPUT_BRAKE_MIN           (0x0750U)
#define IF_INPUT_BRAKE_MAX           (0x0860U)

/* 핸들 보정
 * raw = IF_INPUT_STEER_MIN  -> 0
 * raw = IF_INPUT_STEER_MAX  -> 255
 */
#define IF_INPUT_STEER_MIN           (140U)
#define IF_INPUT_STEER_MAX           (0x0A85U)
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
static if_input_ecu_data_t s_input_data;
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
static uint16 if_input_ecu_is_in_range(uint16 raw, uint16 min, uint16 max);
static uint8 if_input_ecu_clamp_and_scale_to_u8(uint16 raw, uint16 min, uint16 max);
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
void if_input_ecu_init(void)
{
    s_input_data.user_ack_button = drv_button_get_state();

    s_input_data.accel_pedal_value = 0U;
    s_input_data.brake_pedal_value = 0U;
    s_input_data.steer_angle_deg   = 0U;

    s_input_data.accel_valid = 0U;
    s_input_data.brake_valid = 0U;
    s_input_data.steer_valid = 0U;

    s_input_data.accel_raw = 0U;
    s_input_data.brake_raw = 0U;
    s_input_data.steer_raw = 0U;
}

void if_input_ecu_task(void)
{
    uint16 accel_raw;
    uint16 brake_raw;
    uint16 steer_raw;

    uint8 accel_scaled;
    uint8 brake_scaled;
    uint8 steer_scaled;

    accel_raw = drv_adc_input_get_filtered(DRV_ADC_ACCEL);
    brake_raw = drv_adc_input_get_filtered(DRV_ADC_BRAKE);
    steer_raw = drv_adc_input_get_filtered(DRV_ADC_STEER);

    s_input_data.accel_raw = accel_raw;
    s_input_data.brake_raw = brake_raw;
    s_input_data.steer_raw = steer_raw;

    /* 확인 버튼: 누르면 1, 떼면 0 */
    s_input_data.user_ack_button = drv_button_get_state();

    s_input_data.accel_valid = if_input_ecu_is_in_range(accel_raw, IF_INPUT_ADC_MIN, IF_INPUT_ADC_MAX);
    s_input_data.brake_valid = if_input_ecu_is_in_range(brake_raw, IF_INPUT_ADC_MIN, IF_INPUT_ADC_MAX);
    s_input_data.steer_valid = if_input_ecu_is_in_range(steer_raw, IF_INPUT_ADC_MIN, IF_INPUT_ADC_MAX);

    /********************************************/
    /* accel: MIN~MAX -> 0~255 scale            */
    /********************************************/
    accel_scaled = if_input_ecu_clamp_and_scale_to_u8(accel_raw, IF_INPUT_ACCEL_MIN, IF_INPUT_ACCEL_MAX);
    s_input_data.accel_pedal_value = accel_scaled;

    /********************************************/
    /* brake: MIN~MAX -> 0~255 scale            */
    /********************************************/
    brake_scaled = if_input_ecu_clamp_and_scale_to_u8(brake_raw, IF_INPUT_BRAKE_MIN, IF_INPUT_BRAKE_MAX);
    s_input_data.brake_pedal_value = brake_scaled;

    /********************************************/
    /* steer: MIN~MAX -> 0~255 scale            */
    /********************************************/
    steer_scaled = if_input_ecu_clamp_and_scale_to_u8(steer_raw, IF_INPUT_STEER_MIN, IF_INPUT_STEER_MAX);
    s_input_data.steer_angle_deg = steer_scaled;

    drv_button_clear_events();
}

const if_input_ecu_data_t* if_input_ecu_get_data(void)
{
    return &s_input_data;
}

static uint16 if_input_ecu_is_in_range(uint16 raw, uint16 min, uint16 max)
{
    return ((raw >= min) && (raw <= max)) ? 1U : 0U;
}

static uint8 if_input_ecu_clamp_and_scale_to_u8(uint16 raw, uint16 min, uint16 max)
{
    uint16 clamped;
    uint16 normalized;
    uint16 range;

    if (max <= min)
    {
        return 0U;
    }

    if (raw <= min)
    {
        clamped = min;
    }
    else if (raw >= max)
    {
        clamped = max;
    }
    else
    {
        clamped = raw;
    }

    normalized = (uint16)(clamped - min);
    range = (uint16)(max - min);

    return (uint8)(((uint32)normalized * 255U) / (uint32)range);
}
/*********************************************************************************************************************/
