/**********************************************************************************************************************
 * \file Drv_Button.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
#include "Drv_Button.h"
#include "IfxPort.h"
#include "Platform_Types.h"
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
#define DRV_BUTTON_PORT              (&MODULE_P00)
#define DRV_BUTTON_PIN               (4U)
#define DRV_BUTTON_ACTIVE_LEVEL      (0U)
#define DRV_BUTTON_DEBOUNCE_TICKS    (2U)
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
static bool s_button_state = false;
static bool s_prev_button_state = false;
static bool s_pressed_event = false;
static bool s_released_event = false;
static uint16 s_debounce_cnt = 0U;
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
static bool drv_button_read_raw_pressed(void);
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
void drv_button_init(void)
{
    IfxPort_setPinModeInput(DRV_BUTTON_PORT, DRV_BUTTON_PIN, IfxPort_InputMode_pullUp);

    s_button_state = false;
    s_prev_button_state = false;
    s_pressed_event = false;
    s_released_event = false;
    s_debounce_cnt = 0U;
}

void drv_button_task(void)
{
    bool raw_pressed;
    bool new_state;

    raw_pressed = drv_button_read_raw_pressed();
    new_state = raw_pressed;

    if (new_state != s_button_state)
    {
        s_debounce_cnt++;

        if (s_debounce_cnt >= DRV_BUTTON_DEBOUNCE_TICKS)
        {
            s_prev_button_state = s_button_state;
            s_button_state = new_state;
            s_debounce_cnt = 0U;

            if ((s_prev_button_state == false) && (s_button_state == true))
            {
                s_pressed_event = true;
            }
            else if ((s_prev_button_state == true) && (s_button_state == false))
            {
                s_released_event = true;
            }
            else
            {
                /* do nothing */
            }
        }
    }
    else
    {
        s_debounce_cnt = 0U;
    }
}

bool drv_button_get_state(void)
{
    return s_button_state;
}

bool drv_button_get_pressed_event(void)
{
    return s_pressed_event;
}

bool drv_button_get_released_event(void)
{
    return s_released_event;
}

void drv_button_clear_events(void)
{
    s_pressed_event = false;
    s_released_event = false;
}

static bool drv_button_read_raw_pressed(void)
{
    uint8 pin_state;

    pin_state = (uint8)IfxPort_getPinState(DRV_BUTTON_PORT, DRV_BUTTON_PIN);

    return (pin_state == DRV_BUTTON_ACTIVE_LEVEL) ? true : false;
}
/*********************************************************************************************************************/
